version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: some-rabbit
    hostname: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=goodpassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    restart: unless-stopped

volumes:
  rabbitmq_data: